services:

  db:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:7-bookworm
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  
